// Generated by Calepin. Do not edit.

#let config = (
  enabled: false,
  results: none,
  "image-meta": none,
  "source-dir": "",
  source: none,
  "raw-langs": ("python", "r", "mermaid", "dot", "tikz", "d2"),
)
